class ErrorHandler:
    def __init__(self, print):
        self.print = print
        self.source = None
        self.resetErrors()

    def swapSource(self, source):
        prev = self.source
        self.source = source
        return prev

    def resetErrors(self):
        self.hadSyntaxError = False
        self.hadRuntimeError = False

    def syntaxError(self, token, message):
        """An error due to invalid syntax."""
        self.hadSyntaxError = True
        self._show_error(token, "SyntaxError: " + message)

    def analysisError(self, token, message):
        """An error generated by analysing the code."""
        self._show_error(token, "TypeError: " + message)

    def runtimeError(self, token, message):
        """An error generated at runtime."""
        # self.print(f"[line {token.line}] Error : {message}")
        self.hadRuntimeError = True
        self._show_error(token, "RuntimeError: " + message)

    def _show_error(self, token, message):
        lines = self.source.lines
        tokenName = str(token.type).split(".")[-1]
        prefix = f"{token.line}| "
        squigle = "^" * len(token.lexeme)
        self.print(message + f" at {repr(token.lexeme)} ({tokenName})")
        self.print()
        self.print(prefix + lines[token.line - 1])
        self.print(" " * (len(prefix) + token.column - 1) + squigle)
